services:
  db:
    image: mysql:8.4
    container_name: mysql
    networks:
      - project_net
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    container_name: backend
    networks:
      - project_net
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  project_net:
    driver: bridge